Задача 2
as0kir/pro_java_task1 pull request #2
Opened 2024-09-21 06:30 UTC by as0kir

Задача 2

2024-09-23 09:05 UTC, Alexandr056 requested changes
нужны доработки

2024-09-23 09:05 UTC, Alexandr056 commented on src/ru/askir/pro_task2/TestStream.java
> +                .collect(Collectors.toSet())
нет, так вы собираете в новую коллекцию, промежуточную, и снова открываете стрим, а это не оптимально, стримы для того и существуют в частности, что бы избежать промежуточных состояний

2024-09-23 09:05 UTC, Alexandr056 commented on src/ru/askir/pro_task2/TestStream.java
> +                .get();
orElse, orElseThrow… сейчас вы проигнорировали функционал Optional

2024-09-23 09:05 UTC, Alexandr056 commented on src/ru/askir/pro_task2/TestStream.java
> +                .findAny()
findFirst?

2024-09-23 09:05 UTC, Alexandr056 commented on src/ru/askir/pro_task2/TestStream.java
> +                .collect(Collectors.toSet())
снова промежуточная коллекция

2024-09-23 09:05 UTC, Alexandr056 commented on src/ru/askir/pro_task2/TestStream.java
> +                .findAny()
findFirst()

2024-09-23 09:05 UTC, Alexandr056 commented on src/ru/askir/pro_task2/TestStream.java
> +                .findAny().get();
вместо get orElse или orElseThrow, иначе весь смысл Optional потеряли

2024-09-23 09:31 UTC, as0kir commented on src/ru/askir/pro_task2/TestStream.java
> +                .collect(Collectors.toSet())
Исправил

2024-09-23 09:31 UTC, as0kir commented on src/ru/askir/pro_task2/TestStream.java
> +                .get();
Исправил

2024-09-23 09:31 UTC, as0kir commented on src/ru/askir/pro_task2/TestStream.java
> +                .findAny()
Исправил

2024-09-23 09:31 UTC, as0kir commented on src/ru/askir/pro_task2/TestStream.java
> +                .collect(Collectors.toSet())
Исправил

2024-09-23 09:31 UTC, as0kir commented on src/ru/askir/pro_task2/TestStream.java
> +                .findAny()
Исправил

2024-09-23 09:31 UTC, as0kir commented on src/ru/askir/pro_task2/TestStream.java
> +                .findAny().get();
Исправил

2024-09-23 11:32 UTC, as0kir commented
Исправлено

2024-09-26 11:29 UTC, Alexandr056 approved these changes
хорошая работа над ошибками

2024-09-26 12:52 UTC, merged